#!/bin/bash
# CONFIDENTIAL

export SERVICE_PASS=
#export MYSQL_PASS=root
#export SERVICE_PASS=test
export ADMIN_PASS=junk
export DECODE_PASS=junk
export LOGIN_PASS=totem
export ODBC_PASS=junk
export FETCH_PASS=junk
export ZIP_PASS=booboo
#export GIT_USER=totemstan
export GIT_PASS=GITsnivel8194#1
#export LEXISNEXIS=VQNMQCR3CWMKKXMNPDTGMHWDNSPWKD:1CJKRZCVTRMXRFRHPHWXQGNXCQQJGWXBFMVFTNDP
export GOOGLEUSE=017944666033550212559:c1vclesecjc
#export GOOGLEKEY=AIzaSyBp56CJJA0FE5enebW5_4mTssTGaYzGqz8
#export NEO4J_PASS=root
#export LINK_PASS=totempass

export KEY_LEXNEX=VQNMQCR3CWMKKXMNPDTGMHWDNSPWKD:1CJKRZCVTRMXRFRHPHWXQGNXCQQJGWXBFMVFTNDP
export KEY_GOOGLE=017944666033550212559:c1vclesecjc
export KEY_MYSQL=root:root
export KEY_NEO4J=neo4j:root
export KEY_TXMAIL=brian.d.james:COMCASTsnivel1
export KEY_RXMAIL=
export KEY_GIT=totemstan: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
# CONFIDENTIAL
